### ISSUE TITLE
smileys in dark mode

### ISSUE THREAD

**Issue by AhoyLemon** [AhoyLemon/ballpit#61]
![image](https://user-images.githubusercontent.com/3413200/57634854-baf3c880-756b-11e9-8ffc-c1f01274fa4a.png)

**Comment by AhoyLemon** [comment]
Suggestion from @eladavron 

![image](https://user-images.githubusercontent.com/3413200/57635061-16be5180-756c-11e9-82cd-2fe86635b543.png)

**Comment by AhoyLemon** [comment]
Slight adjustment to @eladavron's idea:

![image](https://user-images.githubusercontent.com/3413200/57635346-92200300-756c-11e9-9908-a48cb546780d.png)


```css
img.smiley { drop-shadow(0 0 2px white) drop-shadow(0 0 1px white) drop-shadow(0 0 1px white); }
```

**Comment by AhoyLemon** [comment]
Grayscale, invert, brighten, ignore gifs.

![image](https://user-images.githubusercontent.com/3413200/57635535-f93db780-756c-11e9-81c0-fa1ae3c320fe.png)

```css
img.smiley { filter: grayscale(1) invert(100%) brightness(2); }
img.smiley[src*=".gif"] { filter: none; }
```
